### ISSUE TITLE
Hinweis, dass "Enter" gedrückt werden muss nach Eingabe

### ISSUE THREAD

**Issue by tiemes** [TeamMedienbildungPHZH/MammutJagen#1]
Ansonsten gibt man Zahl ein und nichts passiert. Sollte auch wenn nach Zahleingabe Feld "lost focus" weitergehen.

**Comment by HunterNN** [comment]
Wurde im Commit ec65ceab841da369bb35a5a9f359e2edd893d305 hinzugefügt.
