### ISSUE TITLE
beim Umstellen von linear auf Hash wird gesuchtes Mammut Feld nicht gelöscht

### ISSUE THREAD

**Issue by tiemes** [TeamMedienbildungPHZH/MammutJagen#5]

**Comment by HunterNN** [comment]
![screenshot from 2018-08-13 16-03-04](https://user-images.githubusercontent.com/1898454/44036574-660c46e2-9f12-11e8-9243-e1aaca6446d0.png)
Meinst du dieses Feld? Ansonsten wird alles bei mir zurückgesetzt.

**Comment by tiemes** [comment]
Genau. Diess Feld sollte jeweils gelöscht werden, wenn der Spielmodus gewechselt wird.
